config/routes.rb
Rails.application.routes.draw do
  
  resources :posts

  resources :contacts, only: [:new, :create]

  mount Ckeditor::Engine => '/ckeditor'

  root 'pages#index'
  get '/index' => 'pages#index'
  get '/coaching' => 'pages#coaching'
  get '/blog' => 'pages#blog'
  get '/show/:id' => 'pages#show', as: 'show_post'
  get '/about' => 'pages#about'
  get '/why' => 'pages#why'
  get '/meeting' => 'pages#meeting'
  get '/partners' => 'pages#partners'
  get '/contacts' => 'contacts#new'

  get '/admin' => 'posts#index'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
	has_secure_password
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, :to => :data

  validates_presence_of :data
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, :mount_on => :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/contact.rb
class Contact < MailForm::Base

  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

	def headers
    {
      :subject => "Kapcsolatfelvétel",
      :to => "info@kapcsolatmentes.hu",
      :from => %("#{name}" <#{email}>)
    }
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
     helper_method :current_admin

def current_admin 
  @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id] 
end

def require_admin
  redirect_to '/login' unless current_admin
end

  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new		
	end

	def create
		@contact = Contact.new(params[:contact])
		@contact.request = request
		if @contact.deliver
			flash.now[:error] = nil
		else
			flash.now[:error] = 'Cannot send message'
			render :new
		end
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@posts = Post.order('created_at DESC').limit(6)
	end

	def blog
		@posts = Post.order('created_at DESC')
	end

  def show
    @posts = Post.find(params[:id])
  end

  def about

  end

  def why

  end

	def meeting

	end

 	def partners
  		
 	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :require_admin
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :image, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new 
	end

	def create
	  @admin = Admin.find_by_email(params[:session][:email])
	  if @admin && @admin.authenticate(params[:session][:password])
	    session[:admin_id] = @admin.id
	    redirect_to '/admin'
	  else
	    redirect_to '/login'
	  end 
	end

	def destroy 
		session[:admin_id] = nil 
		redirect_to '/'	 
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/contacts/create.html.erb
<div class="container" id="content-wrap">
<div id="content">
<div class="contacts-page df-text-style">
<h3>Kapcsolat</h3>
<h3>Köszönjük az üzenetét</h3>
<p>Hamarosan válaszolunk</p>
</div>
</div>
</div>

app/views/contacts/new.html.erb
<div class="container" id="content-wrap">
<div id="content">
<div class="contacts-page df-text-style">
<h3>Kapcsolat</h3>
	<div class="row">

		<div class="col-sm-6">
		<p>További információért, kérjük töltse ki az adatlapot. Amint tudunk válaszolunk.</p>
					<ul class="list-unstyled" id="list-contacts">
        	<li> 
<i class="fa fa-user-md fa-lg"></i><a>Bűdi Marianna</a></li> 
                   <li>  <i class="fa fa-envelope-o fa-lg"></i>
                   <a href="mailto:info@kapcsolatmentes.hu">info@kapcsolatmentes.hu</a>
                   </li> 
			
	<li> <i class="fa fa-phone fa-lg"></i><a>+36 70 327-8653</a></li> 
<li class="">
			<i class="fa fa-map-marker fa-lg"></i>
			<a class="">
				<p>1011 Budapest</p>
				<p>Bem rakpart</p>
			</a>
			</li>
                      </ul>
		</div>

		<div class="col-sm-6" id="contacts-form">
			<%= form_for @contact do |f| %>

				<div class="form-group">
				
				<div class="row">
				<div class="col-sm-6">
				<%= f.text_field :name, required: true,placeholder: "Név", class: "form-control" %>
				</div>

				<div class="col-sm-6">
				<%= f.email_field :email, required: true, placeholder: "E-mail", class: "form-control"%>	
				</div>
				</div>
				</div>
				<div class="row">
				<div class="col-sm-12">
				<div class="form-group">
				<%= f.text_area :message, as: :text, placeholder: "Üzenet", rows: "8", class: "form-control" %>
				</div></div>

				<div class="hidden">
				<%= f.label :nickname %><br>
				<%= f.text_field :nickname, hint: 'leave this field blank' %>
				</div>
				<br>

				<div class="col-sm-12">
				<div class="form-group">
				<%= f.submit 'Küldés', class: "btn btn-secondary btn-sm", id: "contacts-send-button" %>
				</div></div>
				</div>
			<% end %>
		</div>

	</div>
	</div>
</div>
</div>

app/views/layouts/_chevron_up.html.erb
<a href="#0" class="cd-top"><i class="fa fa-chevron-circle-up fa-4x"></i></a>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container" id="footer">
	<div class="row" id="footer-content" >

	<div class="col-xs-12 col-sm-4 col-md-4"><h3>Adatvédelem</h3><p>A Kapcsolatmentés.hu oldal számára kiemelt fontosságú látogatói által rendelkezésre bocsátott személyes adatok védelme, a látogatók információs önrendelkezési jogának biztosítása. Cégünk elkötelezi magát a látogatók személyes adatainak oly módon történő kezelése mellett, amely a vonatkozó hatályos jogszabályoknak teljes körűen eleget téve járul hozzá a látogatók biztonságos internetezési lehetőségeinek megteremtéséhez</p></div>

	<div class="col-sm-8">
		<h3>Kapcsolat</h3>
		<ul class="list-unstyled" id="footer-contacts">
			<li>
				<i class="fa fa-user-md fa-lg"></i><a><p>Bűdi Marianna</p></a>
			</li> 
			<li class="">
				<i class="fa fa-envelope-o fa-lg"></i>
				<a class="" href="mailto:info@kapcsolatmentes.hu"><p>info@kapcsolatmentes.hu</p></a>
			</li>
			<li class="">
				<i class="fa fa-phone fa-lg"></i>
				<a class=""><p>+36 70 327-8653</p></a>
			</li>
			<li class="">
				<i class="fa fa-map-marker fa-lg"></i>
				<a class="">
					<p>1011 Budapest</p>
					<p>Bem rakpart</p>
				</a>
			</li>
		</ul>
	</div>
	</div>
	</div>
	</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" id="full-navbar">
<div class="container-fluid container" id="custom-navbar" >
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
       <%= link_to root_path, class: 'navbar-brand' do %>
  <p>Párkapcsolati<br>Coaching</p>
<% end %>
</div>
	<div class="collapse navbar-collapse navbar-right" id="myNavbar">
	<ul class="nav navbar-nav">
	<li class="<%= 'active' if current_page?(root_path) %>"  id="navbar-box"><%= link_to 'Főoldal', root_path %></li>
	<li class="<%= 'active' if current_page?(blog_path) %>"  id="navbar-box"><%= link_to 'Blog', blog_path %></li>
	<li class="<%= 'active' if current_page?(about_path) %>"  id="navbar-box"><%= link_to 'Bemutatkozás', about_path %></li>
	<li class="<%= 'active' if current_page?(coaching_path) %>"  id="navbar-box"><%= link_to 'Coaching', coaching_path %></li>
	<!--
	<li class="<%= 'active' if current_page?(meeting_path) %>"  id="navbar-box"><%= link_to 'Meeting', meeting_path %></li>
	<li class="<%= 'active' if current_page?(why_path) %>"  id="navbar-box"><%= link_to 'Változás', why_path %></li>
	<li class="<%= 'active' if current_page?(partners_path) %>"  id="navbar-box"><%= link_to 'Partnerek', partners_path %></li>
	-->
	<li class="<%= 'active' if current_page?(new_contact_path) %>"  id="navbar-box"><%= link_to 'Kapcsolat', new_contact_path %></li>
	</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Párkapcsolat megmentése – párkapcsolati coaching</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  <meta name="description" content="Ingyenes párkapcsolat fejlesztő online tréning. Párkapcsolati problémák, eltávolodás, konfliktusok, anyós probléma, viták kezelése párkapcsolati coach segítségével- párterápiával a kapcsolatok jelentős része megmenthető, sikerülhet az újrakezdés.Segítek a kihűlt kapcsolat helyrehozásában. Várom szeretettel Budapesten.">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, :async => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

<%= render 'layouts/footer' %>
<%= render 'layouts/chevron_up' %>

</body>
</html>

app/views/pages/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/


var disqus_shortname = 'kapcsolatmentes';
var disqus_identifier = '<%= @posts.id %>';
var disqus_title = '<%= @posts.title %>';


(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//kapcsolatmentes.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/pages/_newests.html.erb
	<div class="row">
			<h1 class="df-text-style">Legfrissebb blog bejegyzéseim</h1>
		<% @posts.each do |post| %>
		<div class="col-sm-4 newest">
			<div class="newest-cover" style="background-image: url('<%= post.image.cover.url %>')">
				<div class="newest-info">
					<div class="newest-info-title">
					<h3><%=link_to post.title.truncate(30), show_post_path(post) %></h3>
					</div>
					<div class="newest-info-description">
					<p><%= strip_tags truncate_html  post.content, :length => 350 %></p>
					</div>
					<button type="button" class="btn btn-secondary btn-sm" id="newest-info-button">
					<%=link_to 'Bővebben', show_post_path(post) %></button>
				</div>      
       		</div>
       		</div> 
    	<% end %>
    </div>

app/views/pages/_newsletter.html.erb
<div class="row" id="newsletter-wrap">
<div class="col-sm-12" id="newsletter-inner">
<div class="row">
<div class="col-sm-12" id="df-text-format">
<h3>Fejlődj a párkapcsolatodban!</h3>

<p>Itt az ideje, hogy végre megtudd, melyek azok a dolgok, amelyek működőképessé

tesznek egy párkapcsolatot!</br>

Fejleszd a személyiséged, tanuld meg, mi építi és mi rombolja a szerelmet és az

összetartozást.</br>

Iratkozz fel a teljesen INGYENES online párkapcsolat - fejlesztő kurzusra!</br></p>
</div>
	<div class="col-sm-3" id="woman-newsletter">

	<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup" style="float:left">
<form action="//herokuapp.us13.list-manage.com/subscribe/post?u=b091613d3a3f85ddf238560d3&amp;id=e1a9ef2744" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>feliratkozás</br>nőknek</h2>
<div class="indicates-required"><span class="asterisk">*</span> kötelező megadni</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">E-mail Cím  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Vezetéknév  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="LNAME" class="required form-control" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Keresztnév  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required form-control" id="mce-FNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b091613d3a3f85ddf238560d3_e1a9ef2744" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Feliratkozom" name="subscribe" id="contacts-send-button" class="btn btn-secondary btn-sm"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->	
	
	</div>

	<div class="col-sm-6" id="newsletter-middle-image"><!--<img class="img-responsive" src="/img/wm.png" align="middle">--></div>

	<div class="col-sm-3" id="man-newsletter">

<div id="mc_embed_signup" style="float:right">
<form action="//herokuapp.us13.list-manage.com/subscribe/post?u=b091613d3a3f85ddf238560d3&amp;id=c8bb0468e1" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<h2>feliratkozás</br>férfiaknak</h2>
<div class="indicates-required"><span class="asterisk">*</span> kötelező megadni</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">E-mail Cím  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-LNAME">Vezetéknév  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="LNAME" class="required form-control" id="mce-LNAME">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Keresztnév  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required form-control" id="mce-FNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_b091613d3a3f85ddf238560d3_c8bb0468e1" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Feliratkozom" name="subscribe" id="contacts-send-button" class="btn btn-secondary btn-sm"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
	</div>
</div>
</div>
</div>

app/views/pages/blog.html.erb
<div class="container" id="content-wrap">
<div id="content">
<% @posts.each do |post| %>

	<div class="row" id="post-list-box">
		<div class="col-sm-12 col-md-8 col-md-offset-2">
		<%= link_to show_post_path(post) do %>
			<div class="" id="post-header" style="background-image: url('<%= post.image.contentimg.url %>');  ">
				<div id="post-header-title">
					<h1 >
						<%= post.title %>
					</h1>
					<p><%= post.created_at.to_date %></p>
				</div>
			</div>
			<% end %>
			<div id="post-content-strip">
			<%= truncate_html post.content, :length => 500 %>
			<%= link_to 'Bővebben...', show_post_path(post) %>
			</div>
			<hr>
		</div>
	</div>

<% end %>
</div>
</div>

app/views/pages/contact.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	</div>
</div>

app/views/pages/index.html.erb
<div class="zoomground-wrap">

	<div class="zoomground"></div>

	<div class="zoomground-logo-wrap">
		<div class="container">
		<div class="row hidden-xs hidden-sm" id="newsletter-coming">
			<div class="col-sm-6" id="newsletter-coming-text">
				<h3>Ha legtöbb embert megkérdeznénk, valószínűleg kevesen lennének, akik azt tudnák mondani,

hogy valaha is komolyabban tanultak a párkapcsolatról és annak működéséről.<br>

Amint ezt felismerjük, már nem is olyan nehéz megértenünk, miért ütközünk nehézségekbe a

szerelemben.<br>
</h3>
<a class="page-scroll" href="#newsletter-wrap">Fejlődj a párkapcsolatodban!</a>
<h3 id="df-sign">Mariann</h3>
			</div>
		</div>
		</div>
	</div>

	<div id="jump-down-button">
		<a class="page-scroll fa fa fa-angle-double-down fa-4x" href="#content-wrap"></a>
	</div>

</div>

<div class="container" id="content-wrap">
	<div id="content">
	<%= render 'pages/newests' %>
	<%= render 'pages/newsletter' %>
	</div>
</div>

app/views/pages/meeting.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	</div>
</div>

app/views/pages/partners.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	</div>
</div>

app/views/pages/show.html.erb
<div class="container" id="content-wrap">
<div id="content">
<div id="show-post-wrap">
<div class="row" id="show-post">
		<div class="col-sm-12 col-md-8 col-md-offset-2">
			<%= link_to '', blog_path, class: 'fa fa-arrow-left fa-2x', id: 'arrow-back' %>
			<div class="" id="post-header" style="background-image: url('<%= @posts.image.contentimg.url %>');  ">
				<div id="post-header-title">
					<h1 >
						<%= @posts.title %>
					</h1>
					<p><%= @posts.created_at.to_date %></p>
				</div>
			</div>

			<div id="post-content-box">
			<%= raw @posts.content.html_safe %>
			</div>
		</div>
</div>

<div class="row" id="show-comment">
	<div class="col-sm-12 col-md-8 col-md-offset-2">
		<hr>
		<div id="post-comment">
			<%= render 'pages/disqus' %>
		</div>
		<hr>
	</div>
</div>
</div>
</div>
</div>

app/views/pages/why.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	</div>
</div>	

app/views/posts/_admin_widget.html.erb
<div id="admin-widget">
<% if current_admin %> 
<div class="row">
<div class="col-sm-12">
<p class="pull-left a-info">
Bejelentkezve mint:<br>
<strong><%= current_admin.email %></strong>
</p>
<p class="pull-right ">
<%= link_to "", logout_path, method: "delete", class: 'fa fa-sign-out fa-2x a-logout-big' %>
</p>
<% else %> 
  <ul> 
    <li><%= link_to "Login", 'login' %></li> 
  </ul> 
<% end %>
</div>
</div>
</div>
<hr>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :class => 'ckeditor' %>
   <!-- <%= f.text_area :content%> -->
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	<%= render "posts/admin_widget" %>
	<div class="row">
	<div class="col-sm-12">
		<%= link_to '', posts_path, class: 'pull-left fa fa-arrow-circle-o-left fa-2x a-back-big' %>
		<%= link_to '', @post, class: 'pull-right fa fa-eye fa-2x a-show-big' %>
	</div>
</div>
		<h1>Editing Post</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container" id="content-wrap">
<div id="content">
<%= render "posts/admin_widget" %>
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>
<%= link_to 'New Post', new_post_path %>
<div class="table-responsive">
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="1"></th>
      <th>Cover</th>
      <th>Title</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
      <td>
      <ul class="list-unstyled">
      <li><%= link_to '', post, class: 'fa fa-eye fa-lg a-show-small' %></li>
      <li><%= link_to '', edit_post_path(post), class: 'fa fa-pencil-square-o fa-lg a-edit-small' %></li>
      <li><%= link_to '', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'fa fa-trash fa-lg a-del-small' %></li>
      </ul>
  
        </td>
        <td  data-toggle="tooltip" data-placement="right" title="<%= post.image %>"><%= image_tag post.image.thumb.url %></td>
        <td><%= post.title %></td>
        
        <td><%= strip_tags truncate_html  post.content, :length => 350 %></td>
        
        
       
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	<%= render "posts/admin_widget" %>
	<div class="row">
	<div class="col-sm-12">
		<%= link_to '', posts_path, class: 'pull-left fa fa-arrow-circle-o-left fa-2x a-back-big' %>
	</div>
</div>
		<h1>New Post</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container" id="content-wrap">
	<div id="content">
	<%= render "posts/admin_widget" %>
	<div class="row">
<div class="col-sm-12">
<%= link_to '', posts_path, class: 'pull-left fa fa-arrow-circle-o-left fa-2x a-back-big'%>
<%= link_to '', edit_post_path(@post), class: 'pull-right fa fa-pencil-square-o fa-2x a-edit-big' %>
</div>
</div>
<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="" id="post-header" style="background-image:url('<%= @post.image.contentimg.url %>');  ">
				<div id="post-header-title">
					<h1 >
						<%= @post.title %>
					</h1>
					<p><%= @post.created_at.to_date %></p>
				</div>
			</div>

			<div id="post-content-box">
			<%= raw @post.content.html_safe %>
			</div>
		</div>
	</div>
	
	</div>
</div>